FROM rust:latest AS builder

RUN rustup target add x86_64-unknown-linux-musl
RUN apt update && apt install -y musl-tools musl-dev nodejs npm
RUN npm i -g npm bunyan
RUN update-ca-certificates
RUN rustup component add clippy rustfmt
RUN cargo install cargo-watch just

WORKDIR /lyonkit-api

COPY ./ .

RUN cargo build -p server

ENV PORT=8080
EXPOSE $PORT

CMD cargo-watch -C crates/server -s 'cargo run | bunyan'