FROM rust:1.63 AS builder

RUN apt update && apt install -y nodejs npm
RUN npm i -g npm bunyan
RUN update-ca-certificates
RUN cargo install cargo-watch just

WORKDIR /lyonkit-api

COPY . .

RUN cargo build && cargo test -p server --no-run

ENV PORT=8080
EXPOSE $PORT

CMD cargo-watch -s 'cargo run | bunyan'